# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ShumovD_UP\Uc_Pra_Ver2-main\ShumovD_UP\Dima3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MonitoringSystem(object):
    def setupUi(self, MonitoringSystem):
        MonitoringSystem.setObjectName("MonitoringSystem")
        MonitoringSystem.resize(941, 680)
        MonitoringSystem.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MonitoringSystem)
        self.centralwidget.setObjectName("centralwidget")
        self.SwapCurs = QtWidgets.QTabWidget(self.centralwidget)
        self.SwapCurs.setGeometry(QtCore.QRect(0, 10, 941, 651))
        self.SwapCurs.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SwapCurs.setObjectName("SwapCurs")
        self.Students = QtWidgets.QWidget()
        self.Students.setObjectName("Students")
        self.NamedOfPageStudents = QtWidgets.QTextEdit(self.Students)
        self.NamedOfPageStudents.setGeometry(QtCore.QRect(20, 10, 911, 41))
        self.NamedOfPageStudents.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 10px;")
        self.NamedOfPageStudents.setObjectName("NamedOfPageStudents")
        self.TableStudent = QtWidgets.QTableWidget(self.Students)
        self.TableStudent.setGeometry(QtCore.QRect(200, 90, 591, 481))
        self.TableStudent.setStyleSheet("")
        self.TableStudent.setObjectName("TableStudent")
        self.TableStudent.setColumnCount(5)
        self.TableStudent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableStudent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableStudent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableStudent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableStudent.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableStudent.setHorizontalHeaderItem(4, item)
        self.StudentFrame = QtWidgets.QFrame(self.Students)
        self.StudentFrame.setGeometry(QtCore.QRect(20, 60, 171, 511))
        self.StudentFrame.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 5px;\n"
"")
        self.StudentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StudentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StudentFrame.setObjectName("StudentFrame")
        self.AddStudentBtn = QtWidgets.QPushButton(self.StudentFrame)
        self.AddStudentBtn.setGeometry(QtCore.QRect(30, 20, 111, 31))
        self.AddStudentBtn.setStyleSheet("background-color: rgb(41, 124, 0);\n"
"border-color: rgb(60, 60, 180);\n"
"color: rgb(255, 255, 255);")
        self.AddStudentBtn.setObjectName("AddStudentBtn")
        self.FashionLine = QtWidgets.QFrame(self.StudentFrame)
        self.FashionLine.setGeometry(QtCore.QRect(20, 60, 118, 3))
        self.FashionLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.FashionLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FashionLine.setObjectName("FashionLine")
        self.EditStudentBtn = QtWidgets.QPushButton(self.StudentFrame)
        self.EditStudentBtn.setGeometry(QtCore.QRect(30, 80, 111, 31))
        self.EditStudentBtn.setStyleSheet("border-color: rgb(60, 60, 180);\n"
"background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.EditStudentBtn.setObjectName("EditStudentBtn")
        self.line = QtWidgets.QFrame(self.StudentFrame)
        self.line.setGeometry(QtCore.QRect(20, 120, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.DelStudentBtn = QtWidgets.QPushButton(self.StudentFrame)
        self.DelStudentBtn.setGeometry(QtCore.QRect(30, 140, 111, 31))
        self.DelStudentBtn.setStyleSheet("border-color: rgb(60, 60, 180);\n"
"background-color: rgb(152, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.DelStudentBtn.setObjectName("DelStudentBtn")
        self.line_2 = QtWidgets.QFrame(self.StudentFrame)
        self.line_2.setGeometry(QtCore.QRect(20, 190, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.FindStudentBtn = QtWidgets.QPushButton(self.StudentFrame)
        self.FindStudentBtn.setGeometry(QtCore.QRect(30, 200, 111, 31))
        self.FindStudentBtn.setStyleSheet("border-color: rgb(60, 60, 180);\n"
"background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.FindStudentBtn.setObjectName("FindStudentBtn")
        self.FindStudentLine = QtWidgets.QLineEdit(self.StudentFrame)
        self.FindStudentLine.setGeometry(QtCore.QRect(10, 250, 151, 20))
        self.FindStudentLine.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-color: rgb(85, 0, 255);")
        self.FindStudentLine.setObjectName("FindStudentLine")
        self.line_3 = QtWidgets.QFrame(self.StudentFrame)
        self.line_3.setGeometry(QtCore.QRect(20, 290, 118, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.textEdit = QtWidgets.QTextEdit(self.StudentFrame)
        self.textEdit.setGeometry(QtCore.QRect(40, 300, 81, 31))
        self.textEdit.setObjectName("textEdit")
        self.FiltrByGroup = QtWidgets.QComboBox(self.StudentFrame)
        self.FiltrByGroup.setGeometry(QtCore.QRect(10, 370, 141, 22))
        self.FiltrByGroup.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: none;")
        self.FiltrByGroup.setObjectName("FiltrByGroup")
        self.textEdit_2 = QtWidgets.QTextEdit(self.StudentFrame)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 350, 111, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.StudentFrame)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 400, 111, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.FiltrByCurs = QtWidgets.QComboBox(self.StudentFrame)
        self.FiltrByCurs.setGeometry(QtCore.QRect(10, 420, 141, 22))
        self.FiltrByCurs.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: none;")
        self.FiltrByCurs.setObjectName("FiltrByCurs")
        self.textEdit_4 = QtWidgets.QTextEdit(self.StudentFrame)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 450, 151, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.FiltrByScience = QtWidgets.QComboBox(self.StudentFrame)
        self.FiltrByScience.setGeometry(QtCore.QRect(10, 470, 141, 22))
        self.FiltrByScience.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: none;")
        self.FiltrByScience.setObjectName("FiltrByScience")
        self.StudentsFrame = QtWidgets.QFrame(self.Students)
        self.StudentsFrame.setGeometry(QtCore.QRect(800, 60, 131, 111))
        self.StudentsFrame.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 5px;\n"
"")
        self.StudentsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StudentsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StudentsFrame.setObjectName("StudentsFrame")
        self.textEdit_9 = QtWidgets.QTextEdit(self.StudentsFrame)
        self.textEdit_9.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.textEdit_9.setObjectName("textEdit_9")
        self.line_7 = QtWidgets.QFrame(self.StudentsFrame)
        self.line_7.setGeometry(QtCore.QRect(7, 50, 121, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.TotalStudentStat = QtWidgets.QLabel(self.StudentsFrame)
        self.TotalStudentStat.setGeometry(QtCore.QRect(10, 70, 111, 21))
        self.TotalStudentStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.TotalStudentStat.setText("")
        self.TotalStudentStat.setObjectName("TotalStudentStat")
        self.textEdit_6 = QtWidgets.QTextEdit(self.Students)
        self.textEdit_6.setGeometry(QtCore.QRect(200, 50, 591, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.frame_4 = QtWidgets.QFrame(self.Students)
        self.frame_4.setGeometry(QtCore.QRect(0, 580, 861, 31))
        self.frame_4.setStyleSheet("background-color: rgb(60, 60, 180);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.SwapCurs.addTab(self.Students, "")
        self.Curs = QtWidgets.QWidget()
        self.Curs.setObjectName("Curs")
        self.NamedOfPageCurs = QtWidgets.QTextEdit(self.Curs)
        self.NamedOfPageCurs.setGeometry(QtCore.QRect(20, 10, 821, 41))
        self.NamedOfPageCurs.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 10px;")
        self.NamedOfPageCurs.setObjectName("NamedOfPageCurs")
        self.CursTable = QtWidgets.QTableWidget(self.Curs)
        self.CursTable.setGeometry(QtCore.QRect(290, 90, 221, 401))
        self.CursTable.setStyleSheet("")
        self.CursTable.setObjectName("CursTable")
        self.CursTable.setColumnCount(2)
        self.CursTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CursTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CursTable.setHorizontalHeaderItem(1, item)
        self.CursFrame = QtWidgets.QFrame(self.Curs)
        self.CursFrame.setGeometry(QtCore.QRect(30, 60, 151, 271))
        self.CursFrame.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 5px;")
        self.CursFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CursFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CursFrame.setObjectName("CursFrame")
        self.AddCursBtn = QtWidgets.QPushButton(self.CursFrame)
        self.AddCursBtn.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.AddCursBtn.setStyleSheet("background-color: rgb(41, 124, 0);\n"
"border-color: rgb(60, 60, 180);\n"
"color: rgb(255, 255, 255);")
        self.AddCursBtn.setObjectName("AddCursBtn")
        self.line_4 = QtWidgets.QFrame(self.CursFrame)
        self.line_4.setGeometry(QtCore.QRect(20, 70, 118, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.DelCursBtn = QtWidgets.QPushButton(self.CursFrame)
        self.DelCursBtn.setGeometry(QtCore.QRect(20, 100, 111, 31))
        self.DelCursBtn.setStyleSheet("background-color: rgb(152, 0, 0);\n"
"border-color: rgb(60, 60, 180);\n"
"color: rgb(255, 255, 255);")
        self.DelCursBtn.setObjectName("DelCursBtn")
        self.FindCursBtn = QtWidgets.QPushButton(self.CursFrame)
        self.FindCursBtn.setGeometry(QtCore.QRect(20, 160, 111, 31))
        self.FindCursBtn.setStyleSheet("border-color: rgb(60, 60, 180);\n"
"background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.FindCursBtn.setObjectName("FindCursBtn")
        self.FindCursLine = QtWidgets.QLineEdit(self.CursFrame)
        self.FindCursLine.setGeometry(QtCore.QRect(10, 220, 131, 20))
        self.FindCursLine.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-color: rgb(85, 0, 255);")
        self.FindCursLine.setObjectName("FindCursLine")
        self.CursStatFrame = QtWidgets.QFrame(self.Curs)
        self.CursStatFrame.setGeometry(QtCore.QRect(610, 60, 221, 401))
        self.CursStatFrame.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 5px;")
        self.CursStatFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CursStatFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CursStatFrame.setObjectName("CursStatFrame")
        self.textEdit_5 = QtWidgets.QTextEdit(self.CursStatFrame)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 10, 181, 41))
        self.textEdit_5.setObjectName("textEdit_5")
        self.line_8 = QtWidgets.QFrame(self.CursStatFrame)
        self.line_8.setGeometry(QtCore.QRect(50, 50, 118, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.TotalCursStat = QtWidgets.QLabel(self.CursStatFrame)
        self.TotalCursStat.setGeometry(QtCore.QRect(10, 80, 201, 41))
        self.TotalCursStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.TotalCursStat.setText("")
        self.TotalCursStat.setObjectName("TotalCursStat")
        self.MostBigCursStat = QtWidgets.QLabel(self.CursStatFrame)
        self.MostBigCursStat.setGeometry(QtCore.QRect(10, 190, 201, 71))
        self.MostBigCursStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.MostBigCursStat.setText("")
        self.MostBigCursStat.setObjectName("MostBigCursStat")
        self.MostLowCursStat = QtWidgets.QLabel(self.CursStatFrame)
        self.MostLowCursStat.setGeometry(QtCore.QRect(10, 300, 201, 71))
        self.MostLowCursStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.MostLowCursStat.setText("")
        self.MostLowCursStat.setObjectName("MostLowCursStat")
        self.textEdit_7 = QtWidgets.QTextEdit(self.Curs)
        self.textEdit_7.setGeometry(QtCore.QRect(290, 50, 221, 41))
        self.textEdit_7.setObjectName("textEdit_7")
        self.frame_5 = QtWidgets.QFrame(self.Curs)
        self.frame_5.setGeometry(QtCore.QRect(0, 560, 871, 41))
        self.frame_5.setStyleSheet("background-color: rgb(60, 60, 180);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.SwapCurs.addTab(self.Curs, "")
        self.Science = QtWidgets.QWidget()
        self.Science.setObjectName("Science")
        self.NamedOfPageScience = QtWidgets.QTextEdit(self.Science)
        self.NamedOfPageScience.setGeometry(QtCore.QRect(0, 10, 851, 41))
        self.NamedOfPageScience.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 10px;")
        self.NamedOfPageScience.setObjectName("NamedOfPageScience")
        self.ScienceTable = QtWidgets.QTableWidget(self.Science)
        self.ScienceTable.setGeometry(QtCore.QRect(240, 100, 301, 371))
        self.ScienceTable.setObjectName("ScienceTable")
        self.ScienceTable.setColumnCount(2)
        self.ScienceTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ScienceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ScienceTable.setHorizontalHeaderItem(1, item)
        self.textEdit_8 = QtWidgets.QTextEdit(self.Science)
        self.textEdit_8.setGeometry(QtCore.QRect(240, 50, 301, 51))
        self.textEdit_8.setObjectName("textEdit_8")
        self.ScienceFrame = QtWidgets.QFrame(self.Science)
        self.ScienceFrame.setGeometry(QtCore.QRect(20, 60, 151, 411))
        self.ScienceFrame.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 5px;")
        self.ScienceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ScienceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ScienceFrame.setObjectName("ScienceFrame")
        self.AddScienceBtn = QtWidgets.QPushButton(self.ScienceFrame)
        self.AddScienceBtn.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.AddScienceBtn.setStyleSheet("background-color: rgb(41, 124, 0);\n"
"border-color: rgb(60, 60, 180);\n"
"color: rgb(255, 255, 255);")
        self.AddScienceBtn.setObjectName("AddScienceBtn")
        self.line_9 = QtWidgets.QFrame(self.ScienceFrame)
        self.line_9.setGeometry(QtCore.QRect(20, 70, 118, 3))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.DelScienceBtn = QtWidgets.QPushButton(self.ScienceFrame)
        self.DelScienceBtn.setGeometry(QtCore.QRect(20, 100, 111, 31))
        self.DelScienceBtn.setStyleSheet("background-color: rgb(152, 0, 0);\n"
"border-color: rgb(60, 60, 180);\n"
"color: rgb(255, 255, 255);")
        self.DelScienceBtn.setObjectName("DelScienceBtn")
        self.EditScienceBtn = QtWidgets.QPushButton(self.ScienceFrame)
        self.EditScienceBtn.setGeometry(QtCore.QRect(20, 160, 111, 31))
        self.EditScienceBtn.setStyleSheet("border-color: rgb(60, 60, 180);\n"
"background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.EditScienceBtn.setObjectName("EditScienceBtn")
        self.FindScienceBtn = QtWidgets.QPushButton(self.ScienceFrame)
        self.FindScienceBtn.setGeometry(QtCore.QRect(20, 230, 111, 31))
        self.FindScienceBtn.setStyleSheet("border-color: rgb(60, 60, 180);\n"
"background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.FindScienceBtn.setObjectName("FindScienceBtn")
        self.FindScienceLine = QtWidgets.QLineEdit(self.ScienceFrame)
        self.FindScienceLine.setGeometry(QtCore.QRect(10, 280, 131, 20))
        self.FindScienceLine.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-color: rgb(85, 0, 255);")
        self.FindScienceLine.setObjectName("FindScienceLine")
        self.frame = QtWidgets.QFrame(self.Science)
        self.frame.setGeometry(QtCore.QRect(610, 60, 231, 371))
        self.frame.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit_10 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_10.setGeometry(QtCore.QRect(10, 10, 201, 41))
        self.textEdit_10.setObjectName("textEdit_10")
        self.line_10 = QtWidgets.QFrame(self.frame)
        self.line_10.setGeometry(QtCore.QRect(40, 50, 118, 3))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.TotalScienceStat = QtWidgets.QLabel(self.frame)
        self.TotalScienceStat.setGeometry(QtCore.QRect(10, 60, 211, 41))
        self.TotalScienceStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.TotalScienceStat.setText("")
        self.TotalScienceStat.setObjectName("TotalScienceStat")
        self.MostBigScienceStat = QtWidgets.QLabel(self.frame)
        self.MostBigScienceStat.setGeometry(QtCore.QRect(10, 140, 211, 71))
        self.MostBigScienceStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.MostBigScienceStat.setText("")
        self.MostBigScienceStat.setObjectName("MostBigScienceStat")
        self.MostLowScienceStat = QtWidgets.QLabel(self.frame)
        self.MostLowScienceStat.setGeometry(QtCore.QRect(10, 250, 211, 71))
        self.MostLowScienceStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.MostLowScienceStat.setText("")
        self.MostLowScienceStat.setObjectName("MostLowScienceStat")
        self.frame_6 = QtWidgets.QFrame(self.Science)
        self.frame_6.setGeometry(QtCore.QRect(0, 560, 871, 61))
        self.frame_6.setStyleSheet("background-color: rgb(60, 60, 180);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.SwapCurs.addTab(self.Science, "")
        self.Group = QtWidgets.QWidget()
        self.Group.setObjectName("Group")
        self.NamedOfPageGroup = QtWidgets.QTextEdit(self.Group)
        self.NamedOfPageGroup.setGeometry(QtCore.QRect(0, 10, 851, 41))
        self.NamedOfPageGroup.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 10px;")
        self.NamedOfPageGroup.setObjectName("NamedOfPageGroup")
        self.frame_7 = QtWidgets.QFrame(self.Group)
        self.frame_7.setGeometry(QtCore.QRect(0, 560, 871, 61))
        self.frame_7.setStyleSheet("background-color: rgb(60, 60, 180);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.GroupTable = QtWidgets.QTableWidget(self.Group)
        self.GroupTable.setGeometry(QtCore.QRect(280, 100, 261, 361))
        self.GroupTable.setObjectName("GroupTable")
        self.GroupTable.setColumnCount(2)
        self.GroupTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(1, item)
        self.textEdit_11 = QtWidgets.QTextEdit(self.Group)
        self.textEdit_11.setGeometry(QtCore.QRect(280, 50, 261, 51))
        self.textEdit_11.setObjectName("textEdit_11")
        self.frame_8 = QtWidgets.QFrame(self.Group)
        self.frame_8.setGeometry(QtCore.QRect(20, 70, 171, 371))
        self.frame_8.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 5px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.AddGroupBtn = QtWidgets.QPushButton(self.frame_8)
        self.AddGroupBtn.setGeometry(QtCore.QRect(30, 30, 111, 31))
        self.AddGroupBtn.setStyleSheet("background-color: rgb(41, 124, 0);\n"
"border-color: rgb(60, 60, 180);\n"
"color: rgb(255, 255, 255);")
        self.AddGroupBtn.setObjectName("AddGroupBtn")
        self.DelGroupBtn = QtWidgets.QPushButton(self.frame_8)
        self.DelGroupBtn.setGeometry(QtCore.QRect(30, 100, 111, 31))
        self.DelGroupBtn.setStyleSheet("background-color: rgb(152, 0, 0);\n"
"border-color: rgb(60, 60, 180);\n"
"color: rgb(255, 255, 255);")
        self.DelGroupBtn.setObjectName("DelGroupBtn")
        self.line_11 = QtWidgets.QFrame(self.frame_8)
        self.line_11.setGeometry(QtCore.QRect(30, 80, 118, 3))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.EditGroupBtn = QtWidgets.QPushButton(self.frame_8)
        self.EditGroupBtn.setGeometry(QtCore.QRect(30, 170, 111, 31))
        self.EditGroupBtn.setStyleSheet("border-color: rgb(60, 60, 180);\n"
"background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.EditGroupBtn.setObjectName("EditGroupBtn")
        self.FindGroupBtn = QtWidgets.QPushButton(self.frame_8)
        self.FindGroupBtn.setGeometry(QtCore.QRect(30, 240, 111, 31))
        self.FindGroupBtn.setStyleSheet("border-color: rgb(60, 60, 180);\n"
"background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.FindGroupBtn.setObjectName("FindGroupBtn")
        self.FindGroupLine = QtWidgets.QLineEdit(self.frame_8)
        self.FindGroupLine.setGeometry(QtCore.QRect(20, 300, 131, 20))
        self.FindGroupLine.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-color: rgb(85, 0, 255);")
        self.FindGroupLine.setObjectName("FindGroupLine")
        self.frame_2 = QtWidgets.QFrame(self.Group)
        self.frame_2.setGeometry(QtCore.QRect(590, 70, 231, 371))
        self.frame_2.setStyleSheet("background-color: rgb(60, 60, 180);\n"
"border-radius: 5px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textEdit_12 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_12.setGeometry(QtCore.QRect(0, 0, 241, 41))
        self.textEdit_12.setObjectName("textEdit_12")
        self.line_12 = QtWidgets.QFrame(self.frame_2)
        self.line_12.setGeometry(QtCore.QRect(50, 50, 118, 3))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.TotalGroupStat = QtWidgets.QLabel(self.frame_2)
        self.TotalGroupStat.setGeometry(QtCore.QRect(10, 70, 211, 41))
        self.TotalGroupStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.TotalGroupStat.setText("")
        self.TotalGroupStat.setObjectName("TotalGroupStat")
        self.MostBigGroupStat = QtWidgets.QLabel(self.frame_2)
        self.MostBigGroupStat.setGeometry(QtCore.QRect(10, 150, 211, 81))
        self.MostBigGroupStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.MostBigGroupStat.setText("")
        self.MostBigGroupStat.setObjectName("MostBigGroupStat")
        self.MostLowGroupStat = QtWidgets.QLabel(self.frame_2)
        self.MostLowGroupStat.setGeometry(QtCore.QRect(10, 270, 211, 81))
        self.MostLowGroupStat.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.MostLowGroupStat.setText("")
        self.MostLowGroupStat.setObjectName("MostLowGroupStat")
        self.SwapCurs.addTab(self.Group, "")
        MonitoringSystem.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MonitoringSystem)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 21))
        self.menubar.setObjectName("menubar")
        MonitoringSystem.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MonitoringSystem)
        self.statusbar.setObjectName("statusbar")
        MonitoringSystem.setStatusBar(self.statusbar)

        self.retranslateUi(MonitoringSystem)
        self.SwapCurs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MonitoringSystem)

    def retranslateUi(self, MonitoringSystem):
        _translate = QtCore.QCoreApplication.translate
        MonitoringSystem.setWindowTitle(_translate("MonitoringSystem", "MainWindow"))
        self.NamedOfPageStudents.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Научная деятельность студентов | список студентов</span></p></body></html>"))
        item = self.TableStudent.horizontalHeaderItem(0)
        item.setText(_translate("MonitoringSystem", "ID"))
        item = self.TableStudent.horizontalHeaderItem(1)
        item.setText(_translate("MonitoringSystem", "ФИО"))
        item = self.TableStudent.horizontalHeaderItem(2)
        item.setText(_translate("MonitoringSystem", "Группа"))
        item = self.TableStudent.horizontalHeaderItem(3)
        item.setText(_translate("MonitoringSystem", "Курс"))
        item = self.TableStudent.horizontalHeaderItem(4)
        item.setText(_translate("MonitoringSystem", "Научная область"))
        self.AddStudentBtn.setText(_translate("MonitoringSystem", "Добавить"))
        self.EditStudentBtn.setText(_translate("MonitoringSystem", "Редактировать"))
        self.DelStudentBtn.setText(_translate("MonitoringSystem", "Удалить"))
        self.FindStudentBtn.setText(_translate("MonitoringSystem", "Поиск"))
        self.textEdit.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">Фильтрация</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">По группам:</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">По курсам:</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">По н. направлениям:</span></p></body></html>"))
        self.textEdit_9.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">Статистика</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Таблица студентов</span></p></body></html>"))
        self.SwapCurs.setTabText(self.SwapCurs.indexOf(self.Students), _translate("MonitoringSystem", "Tab 1"))
        self.NamedOfPageCurs.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Научная деятельность студентов | список курсов</span></p></body></html>"))
        item = self.CursTable.horizontalHeaderItem(0)
        item.setText(_translate("MonitoringSystem", "ID"))
        item = self.CursTable.horizontalHeaderItem(1)
        item.setText(_translate("MonitoringSystem", "Курс"))
        self.AddCursBtn.setText(_translate("MonitoringSystem", "Добавить"))
        self.DelCursBtn.setText(_translate("MonitoringSystem", "Удалить"))
        self.FindCursBtn.setText(_translate("MonitoringSystem", "Поиск"))
        self.textEdit_5.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Статистика</span></p></body></html>"))
        self.textEdit_7.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Таблица курсов</span></p></body></html>"))
        self.SwapCurs.setTabText(self.SwapCurs.indexOf(self.Curs), _translate("MonitoringSystem", "Tab 2"))
        self.NamedOfPageScience.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Научная деятельность студентов | список научных направлений</span></p></body></html>"))
        item = self.ScienceTable.horizontalHeaderItem(0)
        item.setText(_translate("MonitoringSystem", "ID"))
        item = self.ScienceTable.horizontalHeaderItem(1)
        item.setText(_translate("MonitoringSystem", "Н. Направление"))
        self.textEdit_8.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Таблица научных направлений</span></p></body></html>"))
        self.AddScienceBtn.setText(_translate("MonitoringSystem", "Добавить"))
        self.DelScienceBtn.setText(_translate("MonitoringSystem", "Удалить"))
        self.EditScienceBtn.setText(_translate("MonitoringSystem", "Редактировать"))
        self.FindScienceBtn.setText(_translate("MonitoringSystem", "Поиск"))
        self.textEdit_10.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Статистика</span></p></body></html>"))
        self.SwapCurs.setTabText(self.SwapCurs.indexOf(self.Science), _translate("MonitoringSystem", "Страница"))
        self.NamedOfPageGroup.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Научная деятельность студентов | список групп</span></p></body></html>"))
        item = self.GroupTable.horizontalHeaderItem(0)
        item.setText(_translate("MonitoringSystem", "ID"))
        item = self.GroupTable.horizontalHeaderItem(1)
        item.setText(_translate("MonitoringSystem", "Группа"))
        self.textEdit_11.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Таблица групп</span></p></body></html>"))
        self.AddGroupBtn.setText(_translate("MonitoringSystem", "Добавить"))
        self.DelGroupBtn.setText(_translate("MonitoringSystem", "Удалить"))
        self.EditGroupBtn.setText(_translate("MonitoringSystem", "Редактировать"))
        self.FindGroupBtn.setText(_translate("MonitoringSystem", "Поиск"))
        self.textEdit_12.setHtml(_translate("MonitoringSystem", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Статистика</span></p></body></html>"))
        self.SwapCurs.setTabText(self.SwapCurs.indexOf(self.Group), _translate("MonitoringSystem", "Страница"))
